### ISSUE TITLE
NullPointerException và NoClassDefFoundError

### ISSUE THREAD

**Issue by Banbeucmas** [letruongthinh/Mantle-#5]
NPE

`[13:46:42] [Server thread/ERROR]: Error occurred while enabling Mantle v1.0.0 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:91) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at io.lethinh.github.mantle.block.BlockMachine.loadMachinesData(BlockMachine.java:297) ~[?:?]
	at io.lethinh.github.mantle.Mantle.onEnable(Mantle.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]`

NoClassDefFoundError
`java.lang.NoClassDefFoundError: io/lethinh/github/mantle/nbt/NBTTagEnd
	at io.lethinh.github.mantle.block.BlockMachine.writeToNBT(BlockMachine.java:141) ~[?:?]
	at io.lethinh.github.mantle.block.BlockBlockBreaker.writeToNBT(BlockBlockBreaker.java:88) ~[?:?]
	at io.lethinh.github.mantle.block.BlockMachine.saveMachinesInventoriesData(BlockMachine.java:177) ~[?:?]
	at io.lethinh.github.mantle.Mantle.onDisable(Mantle.java:84) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: io.lethinh.github.mantle.nbt.NBTTagEnd
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 12 more`

**Comment by n3sfan** [comment]
Fixed in newer version
